title: My Page
description: いろいろなことを書いていきます！！
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


# For copy button on code
enable_copy_code_button: true


# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# ナビゲーション設定
nav:
  - title: 自己紹介
    url: /about/
  - title: スキル
    url: /skills/
  - title: 実績
    url: /projects/
  - title: 読んだ論文まとめ
    url: /papers/
  - title: GitHub レポジトリ
    url: /repositories/
    

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
